version: '3.8'

services:
    admin:
        build:
            context: .
            args:
                APP_NAME: 'admin'
        container_name: docker-admin
    user:
        build:
            context: .
            args:
                APP_NAME: 'user'
        container_name: docker-user
    gateway:
        image: nginx:1.22.0-alpine
        ports:
            - '80:80'
        volumes:
            - ./gateway.nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - admin
            - user
